# Generated by Django 3.1.5 on 2021-01-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lwin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lwin', models.CharField(max_length=8)),
                ('display_name', models.CharField(max_length=256)),
                ('producer_title', models.CharField(max_length=64)),
                ('producer_name', models.CharField(max_length=64)),
                ('wine', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('region', models.CharField(max_length=64)),
                ('sub_region', models.CharField(max_length=64)),
                ('site', models.CharField(max_length=64)),
                ('parcel', models.CharField(max_length=64)),
                ('colour', models.CharField(max_length=16)),
                ('type', models.CharField(max_length=64)),
                ('sub_type', models.CharField(max_length=64)),
                ('designation', models.CharField(max_length=16)),
                ('classification', models.CharField(max_length=64)),
                ('vintage_cofig', models.CharField(max_length=16)),
                ('first_vintage', models.CharField(max_length=4)),
                ('last_vintage', models.CharField(max_length=4)),
                ('reference', models.CharField(max_length=7)),
            ],
        ),
    ]
