# Generated by Django 3.1.5 on 2021-03-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210309_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='lwin11',
            field=models.CharField(default='', max_length=11),
            preserve_default=False,
        ),
    ]
