# Generated by Django 3.1.5 on 2021-03-12 22:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bottle_lwin11'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
