# Generated by Django 3.1.5 on 2021-03-24 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210312_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bottle',
            old_name='lwin7',
            new_name='lwin',
        ),
    ]
