# Generated by Django 3.1.5 on 2021-05-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210506_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='display_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
