# Generated by Django 3.1.5 on 2021-05-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_consumption_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='display_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
