# Generated by Django 3.1.5 on 2021-05-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_review_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='date_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
