# Generated by Django 3.1.5 on 2021-03-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210324_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='date_added',
            field=models.DateField(),
        ),
    ]
