# Generated by Django 3.1.5 on 2021-03-25 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210325_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
