# Generated by Django 3.1.5 on 2021-05-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210508_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='lwin_country',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='lwin_region',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
