# Generated by Django 3.1.5 on 2021-05-11 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210511_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='lwin_display_name',
        ),
    ]
