# Generated by Django 3.1.5 on 2021-03-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210325_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='store',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
