# Generated by Django 3.1.5 on 2021-03-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210325_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='cellar',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
