# Generated by Django 3.1.5 on 2021-03-25 03:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210325_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='bin',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='colour',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='cost',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='country',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='lwin',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='note',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='producer_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='producer_title',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='region',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='score',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
