# Generated by Django 3.1.5 on 2021-05-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='type',
            field=models.CharField(blank=True, default='Wine', max_length=64, null=True),
        ),
    ]
