# Generated by Django 3.1.5 on 2021-05-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_bottle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
