# Generated by Django 3.1.5 on 2021-03-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210325_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='lwin11',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
