# Generated by Django 3.1.5 on 2021-05-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210517_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='sub_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
