# Generated by Django 3.1.5 on 2021-04-01 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210325_1730'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BottleSize',
        ),
    ]
