# Generated by Django 3.1.5 on 2021-05-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_bottle_permanently_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='lwin_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
