# Generated by Django 3.1.5 on 2021-04-14 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210407_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bottle',
            name='sub_region',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
