# Generated by Django 3.1.5 on 2021-04-20 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210420_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bin',
            name='user',
        ),
    ]
