# Generated by Django 3.1.5 on 2021-04-20 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_bin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.bin'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='cellar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.cellar'),
        ),
    ]
