# Generated by Django 3.1.5 on 2021-04-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_bin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='binname',
            field=models.CharField(max_length=64),
        ),
    ]
