# Generated by Django 3.1.5 on 2021-04-29 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210425_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_tasted', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('vintage', models.CharField(max_length=4)),
                ('is_public', models.BooleanField(default=True)),
                ('like_status', models.CharField(default='like', max_length=64)),
                ('score', models.CharField(blank=True, max_length=3, null=True)),
                ('tasting_note', models.CharField(blank=True, max_length=512, null=True)),
                ('bottle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.bottle')),
                ('lwin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.lwin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=64)),
                ('date_consumed', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('private_note', models.CharField(blank=True, max_length=64, null=True)),
                ('gathered', models.IntegerField(blank=True, default=0, null=True)),
                ('bottle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bottle')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
