# Generated by Django 3.1.5 on 2021-04-29 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_consumption_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='permanently_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='date_consumed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='review',
            name='vintage',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
