# Generated by Django 3.1.5 on 2021-04-29 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20210429_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='vintage',
            new_name='lwin_vintage',
        ),
    ]
